<?php

/**
 * Implements hook_menu().
 */
function feeds_tamper_ui_menu() {
  $items = array();
  $items['admin/structure/feeds/tamper/list/%feeds_importer'] = array(
    'title callback' => 'feeds_tamper_ui_main_title',
    'title arguments' => array(5),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('feeds_tamper_ui_list_form', 5),
    'access arguments' => array('administer feeds_tamper'),
    'file' => 'feeds_tamper_ui.admin.inc',
  );
  $items['admin/structure/feeds/tamper/add/%feeds_importer/%'] = array(
    'title callback' => 'feeds_tamper_ui_add_title',
    'title arguments' => array(6),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('feeds_tamper_ui_add_plugin_form', 5, 6),
    'access arguments' => array('administer feeds_tamper'),
    'file' => 'feeds_tamper_ui.admin.inc',
  );
  $items['admin/structure/feeds/tamper/edit/%feeds_tamper_plugin_instance'] = array(
    'title callback' => 'feeds_tamper_ui_edit_title',
    'title arguments' => array(5),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('feeds_tamper_ui_edit_plugin_form', 5),
    'access arguments' => array('administer feeds_tamper'),
    'file' => 'feeds_tamper_ui.admin.inc',
  );
  $items['admin/structure/feeds/tamper/delete/%feeds_tamper_plugin_instance'] = array(
    'title callback' => 'feeds_tamper_ui_delete_title',
    'title arguments' => array(5),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('feeds_tamper_ui_delete_form', 5),
    'access arguments' => array('administer feeds_tamper'),
    'file' => 'feeds_tamper_ui.admin.inc',
  );
  return $items;
}

function feeds_tamper_plugin_instance_load($instance_id) {
  return feeds_tamper_load_instance($instance_id);
}

function feeds_tamper_ui_add_title($source) {
  return t('Add plugin to: @source', array('@source' => $source));
}

function feeds_tamper_ui_edit_title($instance) {
  if ($instance->export_type == EXPORT_IN_DATABASE) {
    return t('Edit: @id', array('@id' => $instance->description));
  }
  return t('Override: @id', array('@id' => $instance->description));
}

function feeds_tamper_ui_delete_title($instance) {
  if ($instance->export_type == EXPORT_IN_DATABASE) {
    return t('Delete plugin: @id', array('@id', $instance->id));
  }
  return t('Revert plugin: @id', array('@id', $instance->id));
}

function feeds_tamper_ui_main_title($importer) {
  return t('Tamper plugins: @name', array('@name' => $importer->config['name']));
}

function feeds_tamper_ui_theme($existing, $type, $theme, $path) {
  return array(
    'feeds_tamper_ui_list_form' => array(
      'render element' => 'form',
      'file' => 'feeds_tamper_ui.admin.inc',
    ),
  );
}

function feeds_tamper_ui_form_feeds_ui_overview_form_alter(&$form, &$form_state, $form_id) {
  if (!empty($form['enabled'])) {
    foreach ($form['enabled'] as $id => &$table) {
      $table['operations']['#markup'] .= ' | ' . l(t('Tamper'), 'admin/structure/feeds/tamper/list/' . $id);
    }
  }
}

function feeds_tamper_ui_form_feeds_ui_mapping_form_alter(&$form, &$form_state, $form_id) {
  $form['help']['#markup'] .= l(t('Configure Feeds Tamper'), 'admin/structure/feeds/tamper/list/' . $form['#importer']->id);
}
