<?php
// $Id$

// Implements hook_menu.
function feeds_tamper_ui_menu() {
  $items = array();

  $items['admin/structure/feeds_tamper'] = array(
    'title' => 'Feed tamper',
    'description' => 'Configure Feeds tamper to modify incoming feeds data.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('feeds_tamper_ui_overview_form'),
    'access arguments' => array('administer feeds_tamper'),
    'file' => 'feeds_tamper_ui.admin.inc',
  );

  //$items['admin/structure/feeds_tamper/list'] = array(
  //  'title' => t('List'),
  //  'type' => MENU_DEFAULT_LOCAL_TASK,
  //);
  //$items['admin/structure/feeds_tamper/export/%feeds_importer'] = array(
  //  'title' => t('Export'),
  //  'page callback' => 'drupal_get_form',
  //  'page arguments' => array('feeds_ui_export_form', 4),
  //  'access arguments' => array('administer feeds'),
  //  'file' => 'feeds_ui.admin.inc',
  //  'type' => MENU_CALLBACK,
  //);

  $items['admin/structure/feeds_tamper/edit/%feeds_importer'] = array(
    'title' => t('Edit'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('feeds_tamper_ui_edit_form', 4),
    'access arguments' => array('administer feeds_tamper'),
    'file' => 'feeds_tamper_ui.admin.inc',
  );
  $items['admin/structure/feeds_tamper/edit/%feeds_importer/add/%'] = array(
    'title' => t('Add Plugin'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('feeds_tamper_ui_add_plugin_form', 4, 6),
    'access arguments' => array('administer feeds_tamper'),
    'file' => 'feeds_tamper_ui.admin.inc',
  );
  $items['admin/structure/feeds_tamper/edit_plugin/%feeds_tamper_plugin_instance'] = array(
    'title callback' => 'feeds_tamper_ui_edit_title',
    'title arguments' => array(4),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('feeds_tamper_ui_edit_plugin_form', 4),
    'access arguments' => array('administer feeds_tamper'),
    'file' => 'feeds_tamper_ui.admin.inc',
  );
  $items['admin/structure/feeds_tamper/remove_plugin/%feeds_tamper_plugin_instance'] = array(
    'title callback' => 'feeds_tamper_ui_remove_title',
    'title arguments' => array(4),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('feeds_tamper_ui_remove_plugin_form', 4),
    'access arguments' => array('administer feeds_tamper'),
    'file' => 'feeds_tamper_ui.admin.inc',
  );
  return $items;
}

function feeds_tamper_plugin_instance_load($instance_id) {
  return feeds_tamper_load_instance($instance_id);
}

function feeds_tamper_ui_edit_title($instance) {
  if ($instance->export_type == EXPORT_IN_DATABASE) {
    return t('Edit plugin: ') . $instance->id;
  }
  return t('Override plugin: ') . $instance->id;
}
function feeds_tamper_ui_remove_title($instance) {
  if ($instance->export_type == EXPORT_IN_DATABASE) {
    return t('Remove plugin: ') . $instance->id;
  }
  return t('Revert plugin: !id?', array('!id' => $instance->id));
}

function feeds_tamper_ui_theme() {
  return array(
    'feeds_tamper_ui_edit_form' => array(
      'render element' => 'form',
      'file' => 'feeds_tamper_ui.admin.inc',
    ),
  );
}