<?php

/**
 * Feeds hooks.
 */

/**
 * Implements hook_feeds_after_parse().
 *
 * This is the meat of the whole deal.  After every Feeds run, before going into
 * processing, this gets called and modifies the data based on the configuration.
 */
function feeds_tamper_feeds_after_parse(FeedsSource $source, FeedsParserResult $result) {
  $importer_instances = feeds_tamper_load_by_importer($source->importer->id, FALSE, TRUE);
  if (empty($importer_instances)) {
    return;
  }
  $plugins = feeds_tamper_get_plugins();
  foreach ($result->items as $item_key => &$item) {
    foreach ($importer_instances as $element_key => $instances) {
      // Add in empty source, it was lowercased by above. This is a big ol'
      // hack, but it's necessary to accomplish certain things.
      if (strpos($element_key, 'blank source ') === 0) {
        $element_key = drupal_ucfirst($element_key);
        $item[$element_key] = '';
      }
      if (isset($item[$element_key])) {
        foreach ($instances as $instance) {
          $plugin = $plugins[$instance->plugin_id];
          $is_array = is_array($item[$element_key]);

          if ($is_array && $plugin['multi'] == 'loop') {
            foreach ($item[$element_key] as &$i) {
              $plugin['callback']($result, $item_key, $element_key, $i, $instance->settings);
            }
          }
          elseif ($is_array && $plugin['multi'] == 'direct') {
            $plugin['callback']($result, $item_key, $element_key, $item[$element_key], $instance->settings);
          }
          elseif (!$is_array && $plugin['single'] != 'skip') {
            $plugin['callback']($result, $item_key, $element_key, $item[$element_key], $instance->settings);
          }
        }
      }
    }
  }
}

/**
 * Implements hook_feeds_processor_targets_alter().
 */
function feeds_tamper_feeds_processor_targets_alter(&$targets, $entity_type, $bundle_name) {
  $targets['feeds_tamper_store'] = array(
    'name' => t('Temporary target'),
    'description' => t('A field that stores the source data temporarily so that it can be used with the Feeds Tamper rewrite plugin.'),
    'callback' => 'feeds_tamper_do_nothing',
  );
}

/**
 * Implements hook_feeds_parser_sources_alter().
 */
function feeds_tamper_feeds_parser_sources_alter(&$sources, $content_type) {
  $sources['Blank source 1'] = array(
    'description' => t("A source provided by Feeds Tamper with no value of it's own."),
  );
}

/**
 * Do nothing callback for feeds_tamper_feeds_processor_targets_alter().
 */
function feeds_tamper_do_nothing() {}

/**
 * Core hooks.
 */

/**
 * Implements hook_permission().
 */
function feeds_tamper_permission() {
  $perms = array(
    'administer feeds_tamper' => array(
      'title' => t('Administer Feeds Tamper'),
      'description' => t('Create, edit and delete plugins for any importer.'),
    ),
  );
  foreach (feeds_importer_load_all() as $importer) {
    $name = array('@name' => $importer->config['name']);
    $perms['tamper ' . $importer->id] = array(
      'title' => t('Tamper @name feeds', $name),
      'description' => t('Create, edit and delete plugins for @name.', $name),
    );
  }
  return $perms;
}

/**
 * Menu access callback.
 *
 * @param string|FeedsImporter $importer
 *   The importer or importer id being tampered with.
 *
 * @param string|stdClass $instance
 *   If set, the importer attached to $instance will be used.
 *
 * @return bool
 *   Whether or not the user has access.
 */
function feeds_tamper_access($importer, $instance = NULL) {
  if (isset($instance)) {
    if (is_object($instance)) {
      $importer = $instance->importer;
    }
    else {
      $importer = feeds_tamper_load_instance($instance)->importer;
    }
  }
  elseif (is_object($importer)) {
    $importer = $importer->id;
  }

  // Verify actual input if above failed.
  if ($importer) {
    // Check for permissions, otherwise return FALSE.
    if (user_access('administer feeds_tamper') || user_access('tamper ' . $importer)) {
      return TRUE;
    }
  }
  return FALSE;
}

/**
 * Implements hook_form_feeds_ui_mapping_form_alter().
 *
 * This is an interesting bit of work. Each source name has to be unique,
 * but we have no idea how many to create with
 * feeds_tamper_feeds_parser_sources_alter() because we don't know how many
 * targets there are going to be.
 *
 * The solution is to keep track in the form how many have been added.
 */
function feeds_tamper_form_feeds_ui_mapping_form_alter(&$form, &$form_state) {
  $newest_mapping = array();
  //$instances_to_delete = feeds_tamper_load_by_importer($form['#importer']->id, TRUE);
  foreach ($form['#mappings'] as $mapping) {
    if (strpos($mapping['source'], 'Blank source ') === 0) {
      $newest_mapping = $mapping;
    }
    //unset($instances_to_delete[$mapping['source']]);
  }
  if (!empty($newest_mapping)) {
    list(, , $count) = explode(' ', $newest_mapping['source']);
    unset($form['source']['#options']['Blank source 1']);
    $form['source']['#options']['Blank source ' . ++$count] = 'Blank source';
  }
  else {
    $form['source']['#options']['Blank source 1'] = 'Blank source';
  }
  //foreach ($instances_to_delete as $instances) {
  //  foreach ($instances as $instance) {
  //    feeds_tamper_delete_instance($instance);
  //  }
  //}
}

/**
 * Feeds Tamper api functions.
 */

/**
 * Load all plugin instances.
 *
 * @param bool $load_disabled
 *   Whether to load disabled plugin instances.
 *
 * @return array
 *   An array of plugin instances keyed to their id.
 */
function feeds_tamper_load_all_instances($load_disabled = FALSE) {
  $instances = array();
  if (function_exists('ctools_include')) {
    ctools_include('export');
    $configs = ctools_export_crud_load_all('feeds_tamper');
    foreach ($configs as $instance_id => $config) {
      if (!empty($config->id) && ($load_disabled || empty($config->disabled))) {
        $instances[$instance_id] = $config;
      }
    }
  }
  return $instances;
}

/**
 * Load a plugin instance by id.
 *
 * @param string $id
 *   The id of the plugin instance.
 *
 * @return stdClass
 *   A plugin instance object.
 */
function feeds_tamper_load_instance($id) {
  ctools_include('export');
  return ctools_export_crud_load('feeds_tamper', $id);
}

/**
 * Save a plugin instance.
 *
 * @param stdClass $instance
 *   A plugin instance object.
 *
 * @return
 *   If the plugin save failed, returns FALSE. If it succeeded, returns
 *   SAVED_NEW or SAVED_UPDATED, depending on the operation performed.
 */
function feeds_tamper_save_instance($instance) {
  // It's a new instance, give it the heaviest weight.
  if (empty($instance->weight)) {
    $all = feeds_tamper_load_by_importer($instance->importer, TRUE);
    $all = !empty($all[$instance->source]) ? $all[$instance->source] : array();
    $weight = 0;
    foreach ($all as $i) {
      if ($i->weight >= $weight) {
        $weight = $i->weight + 1;
      }
    }
    $instance->weight = $weight;
  }
  return ctools_export_crud_save('feeds_tamper', $instance);
}

/**
 * Delete a single plugin instance.
 *
 * @param string|stdClass $instance
 *   A plugin instance object or the id of a plugin instance.
 */
function feeds_tamper_delete_instance($instance) {
  // Allow for string id or plugin object.
  if (is_scalar($instance)) {
    $instance = feeds_tamper_load_instance($instance);
  }
  ctools_export_crud_delete('feeds_tamper', $instance);
}

/**
 * Load plugin instances by importer id.
 *
 * @param string|FeedsImporter $importer
 *   The importer id, or object to reference.
 *
 * @param bool $disabled
 *   Load disabled plugin instances.
 *
 * @param bool $lower
 *   Make the keys lowercase. Only used internally.
 *
 * @return
 *   An array of plugin instances, keyed by source.
 */
function feeds_tamper_load_by_importer($importer, $disabled = FALSE, $lower = FALSE) {
  if (is_scalar($importer)) {
    $importer = feeds_importer($importer);
  }
  $mappings = $importer->processor->config['mappings'];
  $sources = array();
  foreach ($mappings as $mapping) {
    $sources[] = $mapping['source'];
  }
  ctools_include('export');
  $t = ctools_export_load_object('feeds_tamper', 'conditions', array('importer' => $importer->id));
  $instances = array();
  foreach ($t as $i) {
    if (($disabled || empty($i->disabled)) && in_array($i->source, $sources)) {
      if ($lower) {
        $instances[drupal_strtolower($i->source)][] = $i;
      }
      else {
        $instances[$i->source][] = $i;
      }
    }
  }
  foreach ($instances as &$instance_list) {
    usort($instance_list, '_feeds_tamper_cmp');
  }
  return $instances;
}

/**
 * Comparison callback that sorts by weight, then alphabetically by id.
 */
function _feeds_tamper_cmp($a, $b) {
  // If weights are equal compare id's.
  if ($a->weight == $b->weight) {
    $tmp = array($a->id, $b->id);
    sort($tmp);
    if ($tmp[0] == $a->id) {
      return -1;
    }
    return 1;
  }
  return ($a->weight < $b->weight) ? -1 : 1;
}

/**
 * Get all available plugins.
 *
 * @return array
 *   An array where the keys are the plugin keys and the values
 *   are the plugin info arrays as defined in a plugin include file.
 */
function feeds_tamper_get_plugins() {
  ctools_include('plugins');
  return ctools_get_plugins('feeds_tamper', 'plugins');
}

/**
 * Get a single plugin.
 *
 * @param string $id
 *  The id of a plugin.
 *
 * @return stdClass
 *   A plugin object.
 */
function feeds_tamper_get_plugin($id) {
  ctools_include('plugins');
  return ctools_get_plugins('feeds_tamper', 'plugins', $id);
}

/**
 * CTools stuff.
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function feeds_tamper_ctools_plugin_api($owner, $api) {
  if ($owner == 'feeds_tamper' && $api == 'plugins') {
    return array('version' => 2);
  }
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function feeds_tamper_ctools_plugin_directory($module, $plugin) {
  if ($module == 'feeds_tamper') {
    return 'plugins';
  }
}

/**
 * Implements hook_ctools_plugin_type().
 */
function feeds_tamper_ctools_plugin_type() {
  return array(
    'plugins' => array(
      'use hooks' => FALSE,
      'defaults' => array(
        'validate' => FALSE,
        'multi' => FALSE,
        'category' => 'Other',
        'single' => FALSE,
        'default description' => '',
      ),
    ),
  );
}

/**
 * Return a machine name safe version of a string.
 *
 * @param string $string
 *   String to get machine nameized.
 *
 * @return string
 *   A lowercase string with all values not in [a-z0-9] replaced with an
 *   underscore and shortened to 128 characters.
 */
function feeds_tamper_make_machine($string) {
  return drupal_substr(preg_replace('/[^a-z0-9-]/', '_', drupal_strtolower($string)), 0, 127);
}
